name: release

on:
  workflow_dispatch:

env:
  VERSION: "0.1.0"

jobs:
  verify:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}
